name: Deepfactor scan image
description: Scan a docker image using Deepfactor

inputs:
  image:
    description: The name of the image to deploy, should already be built
    required: true
  deepfactor_run_token:
    description: The deepfactor run token
    required: true

runs:
  using: composite
  steps:
    - name: Deepfactor scan
      env:
        DF_RUN_TOKEN: ${{ inputs.deepfactor_run_token }}
        IMAGE: ${{ inputs.image }}
      shell: bash
      run: docker run --pull=always --rm --env DF_RUN_TOKEN public.ecr.aws/deepfactor/df/runtime:latest dfctl scan $IMAGE
