name: Deepfactor scan image

on:
  workflow_call:
    inputs:
      image:
        description: The name of the image to deploy, should already be built
        required: true
        type: string
    secrets:
      deepfactor_run_token:
        description: The deepfactor run token
        required: true


jobs:
  scan:
    name: Deepfactor scan image
    runs-on: ubuntu-latest
    container: public.ecr.aws/deepfactor/df/runtime:latest
    env:
      DF_RUN_TOKEN: ${{ secrets.deepfactor_run_token }}
      IMAGE: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Scan with Deepfactor
        run: dfctl scan $IMAGE
